[NAMA SALES]
C - M. Fahmi Akbar 

[KODE PELANGGAN]
SG-4126
SG-4141
SG-4130
PW-1019
TGL-1038
TGL-1036
SG-4182
PW-1021
TGL-1029
TGL-1028

[NAMA SALES]
DSR - Hasan Kholidin

[KODE PELANGGAN]
TGL-2021
TGL-2027
PW-1089
PW-1064
PW-1014
TGL-2052
TGL-1004
PW-1005
PW-1006
PW-1067
TGL-2044

[NAMA SALES]
D - Driver

[KODE PELANGGAN]
SG-4135

[PERUSAHAAN]
PTM

[DIVISI]
PCMO

[TANGGAL]
21/07/2026

[INPUT]
FEBIKA

[SS]
url = 
sheet_name = 
