[NAMA SALES]
MGL.RATNO 

[KODE PELANGGAN]
MGL-3055
MGL-3222
MGL-3115
MGL-3419
MGL-3388

[NAMA SALES]
MGL.SPV DANI 

[KODE PELANGGAN]
MGL-3438
MGL-3386
MGL-3427
MGL-3427
YY-1031
MGL-3420

[NAMA SALES]
MGL.YUNO  

[KODE PELANGGAN]
MGL-3269
YY-1033
MGL-1483
MGL-3276
MGL-2112
YY-1157
MGL-1661
MGL-1663
MGL-3472

[PERUSAHAAN]
PTM

[DIVISI]
PCMO

[TANGGAL]
23/06/2026

[INPUT]
Indah
