[NAMA SALES]
DSR - Kristia Devi

[KODE PELANGGAN]
PW-2063 (2)
PW-2048
KOSONG

[NAMA SALES]
C - Samsul Aziz

[KODE PELANGGAN]
PWT-3158
PWT-2068

[PERUSAHAAN]
SBB

[DIVISI]
MCO

[TANGGAL]
03/08/2026

[INPUT]
FEBIKA

[GIRO]
giro_stats = Ya
giro_cut = 1000

[PPRINT]
status = No

[PURE]
pr_process = Ya

[SS]
url = 
sheet_name = 

[PENDING]
pend_stats = No
pend_url = 
pend_sheet = 
pend_col_key = 
pend_col_ret = 

[MASTER]
masdatus = No
url = 
mas_sheet = 
mas_col_key = NOPEL
mas_col_ret = NAMA PELANGGAN
